version: "2.3"

services:
  conductor-server:
    environment:
      - CONFIG_PROP=/app/config/config-aws-external.properties
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-conductor}
      - DB_USER=${DB_USER:-conductor}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - AWS_REGION=${AWS_REGION:-ap-south-1}
    network_mode: "host"
    extra_hosts:
      - "fermiflow-redis.gjxxcu.0001.aps1.cache.amazonaws.com:10.0.3.151"
    image: conductor:server
    container_name: conductor-server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    # networks:
    #   - internal
    ports:
      - 8080:8080
      - 8127:5000
    healthcheck:
      test: ["CMD", "curl", "-I", "-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    depends_on:
      conductor-elasticsearch:
        condition: service_healthy
    volumes:
      - ./server/config:/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9201:9200
    healthcheck:
      test: curl http://localhost:9200/_cluster/health -o /dev/null
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  esdata-conductor:
    driver: local

networks:
  internal:
